### ISSUE TITLE
Consider rsrtools for psarc archive management

### ISSUE THREAD

**Issue by biggestsonicfan** [coatlessali/HoneyPatcher#1]
I see you include a lot of binary blobs in this repo. It would be simpler to have a cross platform dependency to handle the psarc archives. I see that [rsrtools](https://pypi.org/project/rsrtools/#psarc-handling) handles psarc files, and could be imported to use without the unlicensed linux software.

**Comment by coatlessali** [comment]
This would be great. Unfortunately I'm stuck in bed sick at the moment, but I'll see about getting this worked in soon.

Thanks for bringing it to my attention!

Sent from Proton Mail Android

-------- Original Message --------

**Comment by coatlessali** [comment]
Wanted to go ahead and give an update on this. I'm currently working on rewriting HoneyPatcher using Godot w/C# to try to eliminate some of the packaging headaches PyInstaller is giving me - hence why the Linux version was taken down. This is proving particularly troublesome on Steam Deck. If it takes too much longer, I'll go ahead and do this, but given that I'm trying to get away from Python as we speak, there's not a lot of motivation for me to do so.

I thank you again though for the issue, and bringing this to my attention. Leaving this open in case I do end up needing to come back to it.

**Comment by coatlessali** [comment]
The Godot port is about to be released. Closing this issue as its no longer relevant.
